ODK.Website/Models/EventSidebarViewModel.cs
using System;
using System.Collections.Generic;
using ODK.Umbraco.Events;
using ODK.Umbraco.Members;
using ODK.Umbraco.Payments;

namespace ODK.Website.Models
{
    public class EventSidebarViewModel
    {
        public int EventId { get; set; }

        public int MemberId { get; set; }

        public EventResponseType MemberResponse { get; set; }

        public Dictionary<EventResponseType, IReadOnlyCollection<MemberModel>> MemberResponses { get; set; }
            = new Dictionary<EventResponseType, IReadOnlyCollection<MemberModel>>();

        public EventPaymentModel EventPaymentModel { get; set; }

        public double? TicketCost { get; set; }

        public int? TicketCount { get; set; }

        public DateTime? TicketDeadline { get; set; }

        public int? TicketsRemaining { get; set; }
    }
}

ODK.Website/Models/PersonThumbnailViewModel.cs
using ODK.Umbraco.Members;
using Umbraco.Core.Models;
using Umbraco.Web;

namespace ODK.Website.Models
{
    public class PersonThumbnailViewModel
    {
        public PersonThumbnailViewModel(MemberModel member, bool showFullName = true)
        {
            FullName = member.FullName;
            MemberId = member.Id;
            PersonPageUrl = member.Chapter.GetPropertyValue<IPublishedContent>("personPage").Url;
            Picture = member.Picture;
            ShowFullName = showFullName;
        }

        public string FullName { get; }

        public int MemberId { get; }

        public string PersonPageUrl { get; }

        public IPublishedContent Picture { get; }

        public bool ShowFullName { get; }
    }
}

ODK.Website/ViewModels/EventSidebarViewModel.cs
using System.Collections.Generic;
using ODK.Umbraco.Events;
using ODK.Umbraco.Members;

namespace ODK.Website.ViewModels
{
    public class EventSidebarViewModel
    {
        public int EventId { get; set; }

        public EventResponseType MemberResponse { get; set; }

        public Dictionary<EventResponseType, IReadOnlyCollection<MemberModel>> MemberResponses { get; set; }
            = new Dictionary<EventResponseType, IReadOnlyCollection<MemberModel>>();
    }
}

ODK.Website/ViewModels/PersonThumbnailViewModel.cs
using ODK.Umbraco.Members;
using Umbraco.Core.Models;
using Umbraco.Web;

namespace ODK.Website.ViewModels
{
    public class PersonThumbnailViewModel
    {
        public PersonThumbnailViewModel(MemberModel member, bool showFullName = true)
        {
            FullName = member.FullName;
            MemberId = member.Id;
            PersonPageUrl = member.Chapter.GetPropertyValue<IPublishedContent>("personPage").Url;
            Picture = member.Picture;
            ShowFullName = showFullName;
        }

        public string FullName { get; }

        public int MemberId { get; }

        public string PersonPageUrl { get; }

        public IPublishedContent Picture { get; }

        public bool ShowFullName { get; }
    }
}

ODK.Website/Controllers/EventsController.cs
using System.Linq;
using System.Web.Mvc;
using ODK.Umbraco.Events;
using ODK.Umbraco.Payments;
using ODK.Umbraco.Settings;
using ODK.Umbraco.Web.Mvc;
using ODK.Website.Models;
using Umbraco.Core.Models;

namespace ODK.Website.Controllers
{
    public class EventsController : OdkSurfaceControllerBase
    {
        private readonly EventService _eventService;

        public EventsController(EventService eventService)
        {
            _eventService = eventService;
        }

        [ChildActionOnly]
        [HttpGet]
        public ActionResult EventSidebar(int eventId)
        {
            return EventSidebarView(eventId);
        }

        [HttpPost]
        public ActionResult EventSidebar(int eventId, EventResponseType responseType)
        {
            if (CurrentMemberModel == null)
            {
                return RedirectToCurrentUmbracoPage();
            }

            IPublishedContent content = Umbraco.TypedContent(eventId);
            EventModel @event = _eventService.GetEvent(content);

            if (_eventService.IsTicketedEvent(@event))
            {
                return RedirectToCurrentUmbracoPage();
            }

            _eventService.UpdateEventResponse(Umbraco.TypedContent(eventId), CurrentMember, responseType);

            return EventSidebarView(eventId);
        }

        private ActionResult EventSidebarView(int eventId)
        {
            EventSidebarViewModel viewModel = new EventSidebarViewModel
            {
                EventId = eventId
            };

            IPublishedContent content = Umbraco.TypedContent(eventId);
            EventModel @event = _eventService.GetEvent(content);

            if (CurrentMember != null)
            {
                viewModel.MemberId = CurrentMember.Id;
                viewModel.MemberResponses = _eventService.GetEventResponses(eventId, Umbraco);

                if (@event.TicketCost != null)
                {
                    viewModel.EventPaymentModel = new EventPaymentModel(content, content.HomePage(), CurrentMemberModel, @event);

                    viewModel.TicketCost = @event.TicketCost;
                    viewModel.TicketCount = @event.TicketCount;
                    viewModel.TicketDeadline = @event.TicketDeadline;

                    if (viewModel.TicketCount != null)
                    {
                        viewModel.TicketsRemaining = viewModel.TicketCount - 
                            (viewModel.MemberResponses.ContainsKey(EventResponseType.Yes) ? viewModel.MemberResponses[EventResponseType.Yes].Count : 0);
                    }
                }                

                foreach (EventResponseType key in viewModel.MemberResponses.Keys)
                {
                    if (viewModel.MemberResponses[key].Any(x => x.Id == CurrentMember.Id))
                    {
                        viewModel.MemberResponse = key;
                        break;
                    }
                }
            }

            return PartialView("Events/EventSidebar", viewModel);
        }
    }
}

ODK.Website/Views/Partials/BlogpostMeta.cshtml
@model IPublishedContent
@{
    IEnumerable<string> categories = Model.GetPropertyValue<IEnumerable<string>>("categories");
}

<div class="small">@Model.CreateDate.ToString("dd MMMM yyyy")</div>
<div class="small">@Html.Partial("~/Views/Partials/CategoryLinks.cshtml", categories)</div>

ODK.Website/Views/Partials/CategoryLinks.cshtml
@model IEnumerable<string>
@foreach (var category in Model)
{
    <!-- TODO: Add links to categories-->
    <span class="badge badge-light">@category</span>
}

ODK.Website/Views/Partials/Content.cshtml
@using ODK.Umbraco.Content;
@using ODK.Umbraco.Web.Mvc;
@inherits OdkUmbracoTemplatePage
@{
    if (!Model.Content.HasChildContent("bodyText"))
    {
        return;
    }
}

<div class="content">
    @Html.GetGridHtml(Model.Content, "bodyText", "bootstrap3-fluid")
</div>

ODK.Website/Views/Partials/EventSidebar.cshtml
@using ODK.Umbraco.Events;
@using ODK.Umbraco.Members;
@using ODK.Umbraco.Web.Mvc;
@using ODK.Website.Models;
@model EventSidebarViewModel

@if (Model.MemberId > 0)
{
    <div class="card">
        <div class="card-header">
            RSVP
        </div>
        <div class="card-body">
            @using (Html.BeginForm("EventSidebar", "Events", FormMethod.Post, new { @class = "content--ajax" }))
            {
                <input type="hidden" name="eventId" value="@Model.EventId" />
                <input type="hidden" name="responseType" data-submit-value />
                <div class="text-center row">
                    @RenderResponseOption(EventResponseType.Yes)
                    @RenderResponseOption(EventResponseType.Maybe)
                    @RenderResponseOption(EventResponseType.No)
                </div>
                if (Model.MemberResponse != EventResponseType.None)
                {
                    <div class="text-center mt-2">
                        You have replied <strong>@Model.MemberResponse.ToString().ToLower()</strong> to this event
                    </div>
                }
            }
        </div>
    </div>
}


@RenderMemberResponses(EventResponseType.Yes)
@RenderMemberResponses(EventResponseType.Maybe)
@RenderMemberResponses(EventResponseType.No)

@helper RenderMemberResponses(EventResponseType responseType)
{
    if (!Model.MemberResponses.ContainsKey(responseType))
    {
        return;
    }

    IReadOnlyCollection<MemberModel> members = Model.MemberResponses[responseType];
    if (members.Count == 0)
    {
        return;
    }

    string title =
        responseType == EventResponseType.Yes
        ? "Going"
        : responseType == EventResponseType.Maybe
        ? "Maybe"
        : "Not going";

    <div class="card">
        <div class="card-header">
            <a href="#" data-toggle="collapse" data-target="#responses-@responseType">@title (@members.Count)</a>
        </div>
        <div id="responses-@responseType" class="card-body event-attendees collapse @(responseType == EventResponseType.Yes ? "show" : null)">
            <div class="row">
                @foreach (MemberModel member in members)
                {
                    PersonThumbnailViewModel viewModel = new PersonThumbnailViewModel(member, false);

                    <div class="col-3 col-md-4">
                        @Html.Partial("PersonThumbnail", new OdkUmbracoTemplateModel<PersonThumbnailViewModel>(viewModel, null))
                    </div>
                }
            </div>
        </div>
    </div>
}

@helper RenderResponseOption(EventResponseType responseType)
{
    <button type="button" class="btn-icon event-response-option col-4 align-middle @ActiveIf(Model.MemberResponse == responseType)" data-submit data-value="@responseType">
        @Html.Partial("EventResponseIcon", responseType)
    </button>
}

@helper ActiveIf(bool condition)
{
    if (!condition)
    {
        return;
    }

    @Html.Raw("active")
}

ODK.Website/Views/Partials/Feedback.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    string[] messages = TempData["Feedback.Messages"] as string[];
    if (messages == null || messages.Length == 0)
    {
        return;
    }

    bool[] successes = TempData["Feedback.Successes"] as bool[];
    if (successes == null || messages.Length != successes.Length)
    {
        return;
    }
}

<div class="container">
    @for (int i = 0; i < messages.Length; i++)
    {
        @RenderMessage(messages[i], successes[i])
    }
</div>

@helper RenderMessage(string message, bool success)
{
    if (string.IsNullOrEmpty(message))
    {
        return;
    }

    string alertType = success ? "success" : "warning";
    <div class="alert alert-@alertType alert-dismissible fade show mt-3" role="alert">
        @message
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

ODK.Website/Views/Partials/Form.cshtml
@using Newtonsoft.Json.Linq;
@model JArray

@foreach (JToken field in Model)
{
    <div>
        @RenderField(field)
    </div>
}

@helper RenderField(JToken field)
{
    string name = field.Value<string>("formName");
    string label = field.Value<string>("formLabel");
    string subLabel = field.Value<string>("formSublabel");
    string type = field.Value<string>("formType");
    string options = field.Value<string>("formOptions");
    bool required = field.Value<string>("formRequired") == "True";

    <div class="form-group @(required ? "required" : null)">
        @if (type != "CheckBox")
        {
            @Label(name, label, subLabel)
        }

        @switch (type)
        {
            case "DropDownList":

                <select id="@name" name="@name" class="form-control" @(required ? "required" : null)>
                    <option value="">Please select...</option>
                    @foreach (string option in options.Split('|'))
                    {
                        <option>@option</option>
                    }
                </select>
                break;

            case "CheckBox":
                <div class="form-check">
                    <input id="@name" name="@name" type="checkbox" class="form-check-input" @(required ? "required" : null) value="true">
                    <input type="hidden" value="false" name="@name" />
                    @Label(name, label, subLabel, "form-check-label")
                </div>
                break;
        }
    </div>

}

@helper Label(string name, string label, string subLabel, string cssClass = "form-control-label")
{
    <label for="@name" class="@cssClass">@Html.Raw(label)</label>
    if (!string.IsNullOrEmpty(subLabel))
    {
        <span class="text-muted">@subLabel</span>
    }
}

ODK.Website/Views/Partials/MemberForm.cshtml
@using ODK.Umbraco.Members;
@using ODK.Umbraco.Web.Mvc;
@model OdkUmbracoTemplateModel<MemberModel>
@{
    IEnumerable<SelectListItem> knittingExperienceOptions = Model.Helper.GetKnittingExperienceOptions().Select(x => new SelectListItem
    {
        Value = x.Value,
        Text = x.Value
    });

    RegisterMemberModel registerMember = Model.Value as RegisterMemberModel;
    UpdateMemberModel updateMember = Model.Value as UpdateMemberModel;

    HtmlHelper<MemberModel> memberHelper = Html.For<MemberModel>(Model.Value);
    HtmlHelper<RegisterMemberModel> registerHelper = registerMember != null ? Html.For<RegisterMemberModel>(registerMember) : null;
    HtmlHelper<UpdateMemberModel> updateHelper = updateMember != null ? Html.For<UpdateMemberModel>(updateMember) : null;
}

<div class="form-group required">
    @memberHelper.LabelFor(x => x.Email, new { @class = "form-control-label" })
    @memberHelper.TextBoxFor(x => x.Email, new { type = "email", @class = "form-control", required = "" })
    @memberHelper.ValidationMessageFor(x => x.Email)
</div>

<div class="form-group">
    <div class="form-check">
        @memberHelper.CheckBoxFor(x => x.EmailOptIn, new { @class = "form-check-input" })
        @memberHelper.LabelFor(x => x.EmailOptIn, new { @class = "form-control-label form-check-label" })
        <span class="text-muted">Opt in to emails informing you of upcoming events</span>
    </div>
</div>

@if (registerHelper != null)
{
    <div class="form-group required">
        <div class="form-row">
            <div class="col-6">
                @registerHelper.LabelFor(x => x.Password, new { @class = "form-control-label" })
                @registerHelper.TextBoxFor(x => x.Password, new { type = "password", @class = "form-control", required = "" })
                @registerHelper.ValidationMessageFor(x => x.Password)
            </div>
            <div class="col-6">
                @registerHelper.LabelFor(x => x.PasswordConfirm, new { @class = "form-control-label" })
                @registerHelper.TextBoxFor(x => x.PasswordConfirm, new { type = "password", @class = "form-control", required = "" })
                @registerHelper.ValidationMessageFor(x => x.PasswordConfirm)
            </div>
        </div>
    </div>
}

<div class="form-group required">
    <div class="form-row">
        <div class="col-6">
            @memberHelper.LabelFor(x => x.FirstName, new { @class = "form-control-label" })
            @memberHelper.TextBoxFor(x => x.FirstName, new { @class = "form-control", required = "" })
            @memberHelper.ValidationMessageFor(x => x.FirstName)
        </div>
        <div class="col-6">
            @memberHelper.LabelFor(x => x.LastName, new { @class = "form-control-label" })
            @memberHelper.TextBoxFor(x => x.LastName, new { @class = "form-control", required = "" })
            @memberHelper.ValidationMessageFor(x => x.LastName)
        </div>
    </div>
</div>

@if (registerHelper != null)
{
    <div class="form-group required">
        @registerHelper.LabelFor(x => x.UploadedPicture, new { @class = "form-control-label" })
        <div class="input-group mb-3">
            <div class="custom-file">
                <input type="file" class="custom-file-input" accept="image/*"
                       name="@registerHelper.NameFor(x => x.UploadedPicture)" id="@registerHelper.IdFor(x => x.UploadedPicture)">
                <label class="custom-file-label" for="@registerHelper.NameFor(x => x.UploadedPicture)">Choose file</label>
            </div>
        </div>
        @registerHelper.ValidationMessageFor(x => x.UploadedPicture)
    </div>
}
else if (updateHelper != null)
{
    <div class="form-group">
        @updateHelper.LabelFor(x => x.UploadedPicture, new { @class = "form-control-label" })
        <div class="input-group mb-3">
            <div class="custom-file">
                <input type="file" class="custom-file-input" accept="image/*"
                       name="@updateHelper.NameFor(x => x.UploadedPicture)" id="@updateHelper.IdFor(x => x.UploadedPicture)">
                <label class="custom-file-label" for="@updateHelper.NameFor(x => x.UploadedPicture)">Choose file</label>
            </div>
        </div>
        @updateHelper.ValidationMessageFor(x => x.UploadedPicture)
    </div>
}

<div class="form-group">
    @memberHelper.LabelFor(x => x.Neighbourhood, new { @class = "form-control-label" })
    @Html.Partial("Tooltip", "For other Knitwits to see who's nearby")
    @memberHelper.TextBoxFor(x => x.Neighbourhood, new { @class = "form-control" })
    @memberHelper.ValidationMessageFor(x => x.Neighbourhood)
</div>

<div class="form-group">
    @memberHelper.LabelFor(x => x.Hometown, new { @class = "form-control-label" })
    @Html.Partial("Tooltip", "Your hometown")
    @memberHelper.TextBoxFor(x => x.Hometown, new { @class = "form-control" })
    @memberHelper.ValidationMessageFor(x => x.Hometown)
</div>

<div class="form-group required">
    @memberHelper.LabelFor(x => x.FavouriteBeverage, new { @class = "form-control-label" })
    @memberHelper.TextBoxFor(x => x.FavouriteBeverage, new { @class = "form-control", required = "" })
    @memberHelper.ValidationMessageFor(x => x.FavouriteBeverage)
</div>

<div class="form-group required">
    @memberHelper.LabelFor(x => x.KnittingExperience, new { @class = "form-control-label" })
    <label class="text-muted">You don't have to be a great knitter to be a Drunken Knitwit!</label>
    @memberHelper.DropDownListFor(x => x.KnittingExperience, knittingExperienceOptions, "Select...", new { @class = "form-control" })
    @memberHelper.ValidationMessageFor(x => x.KnittingExperience)
</div>

<div class="form-group required" data-other-for="@memberHelper.IdFor(x => x.KnittingExperience)" data-other-key="@knittingExperienceOptions.Last().Value">
    @memberHelper.LabelFor(x => x.KnittingExperienceOther, new { @class = "form-control-label", required = "" })
    @memberHelper.TextBoxFor(x => x.KnittingExperienceOther, new { @class = "form-control" })
    @memberHelper.ValidationMessageFor(x => x.KnittingExperienceOther)
</div>

<div class="form-group required">
    @memberHelper.LabelFor(x => x.Reason, new { @class = "form-control-label" })
    @memberHelper.TextAreaFor(x => x.Reason, new { rows = 3, @class = "form-control", required = "", maxlength = 500 })
    @memberHelper.ValidationMessageFor(x => x.Reason)
</div>

<div class="form-group">
    @memberHelper.LabelFor(x => x.FacebookProfile, new { @class = "form-control-label" })
    @Html.Partial("Tooltip", "This is optional, and only other members will be able to see it.")
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text">
                <span class="d-none d-md-inline">https://www.facebook.com/</span>
                <span class="d-md-none"><i class="fa fa-facebook-square"></i>&nbsp;<span class="align-middle">/</span></span>
            </span>
        </div>
        @memberHelper.TextBoxFor(x => x.FacebookProfile, new { @class = "form-control" })
    </div>
    @memberHelper.ValidationMessageFor(x => x.FacebookProfile)
</div>

@if (Model.Value.Joined != null)
{
    <div class="form-group">
        @memberHelper.LabelFor(x => x.Joined, new { @class = "form-control-label" })
        <span class="form-control-plaintext">@Model.Value.Joined.Value.ToString("dd MMMM yyyy")</span>
    </div>
}

@if (Model.Value.Type != MemberTypes.None)
{
    <div class="form-group">
        @memberHelper.LabelFor(x => x.Type, new { @class = "form-control-label" })
        <span class="form-control-plaintext">@Model.Value.Type</span>
    </div>
}

@helper RequiredIf(bool condition)
{
    if (!condition)
    {
        return;
    }

    @Html.Raw("required")
}

ODK.Website/Views/Partials/PageHeader.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    string title = Model.Content.GetPropertyValue<string>("PageTitle") ?? Model.Content.Name;
}

<section class="section section--header">
    <div class="container">
        <h1>@title</h1>
    </div>
</section>

ODK.Website/Views/Partials/PaymentButton.cshtml
@using ODK.Payments;
@using ODK.Umbraco.Payments;
@model PaymentModel
@{
    PaymentProviderType provider;
    if (!Enum.TryParse<PaymentProviderType>(Model.Provider, out provider))
    {
        return;
    }
}

@if (provider == PaymentProviderType.Stripe)
{
    string formId = string.Format("stripe-form-{0}", Model.Id);

    using (Html.BeginUmbracoForm("Create", "Stripe", null, new { id = formId }, FormMethod.Post))
    {
        <div>
            <input type="hidden" name="id" value="@Model.Id" />
            <input type="hidden" class="js-cancel-url" name="cancelUrl" value="@Request.Url" />

            <button class="btn btn-primary">
                Purchase
            </button>
            <span>@Model.CurrencyString</span>
        </div>
    }
}

ODK.Website/Views/Partials/PersonThumbnail.cshtml
@using ODK.Umbraco.Web.Mvc;
@using ODK.Website.Models;
@model OdkUmbracoTemplateModel<PersonThumbnailViewModel>
@{
    PersonThumbnailViewModel viewModel = Model.Value;
    string memberUrl = viewModel.PersonPageUrl + "?id=" + viewModel.MemberId;
}

<div id="member-@viewModel.MemberId" class="card member-tile">
    <a href="@memberUrl">
        @if (viewModel.Picture != null)
        {
            <img class="card-img-top" src="@viewModel.Picture.GetCropUrl(height: 150, width: 150)" alt="Photo of @viewModel.FullName"
                 data-toggle="tooltip" title="@(viewModel.ShowFullName ? null : viewModel.FullName)">
        }

        @if (viewModel.ShowFullName)
        {
            <div class="search-field member-tile__footer">
                @viewModel.FullName
            </div>
        }
    </a>
</div>

ODK.Website/Views/Partials/SectionHeader.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    string title = Model.Content.GetPropertyValue<string>("PageTitle") ?? Model.Content.Name;
}

<section class="section section--header">
    <div class="container">
        <h1>@title</h1>
    </div>
</section>

ODK.Website/Views/Partials/Tooltip.cshtml
@model string

<i class="icon--help fa fa-question-circle" data-toggle="tooltip" title="@Model"></i>

ODK.Website/Views/Partials/TopNavigation.cshtml
@using ODK.Umbraco.Content;
@using ODK.Umbraco.Members;
@inherits ODK.Umbraco.Web.Mvc.OdkUmbracoTemplatePage
@{
    IPublishedContent homePage = HomePage;
    IPublishedContent member = CurrentMember;
    MemberModel memberModel = CurrentMemberModel;

    IEnumerable<IEnumerable<IPublishedContent>> menuItemGroups = homePage.MenuItemGroups(member, 5);

    IPublishedContent logo = HomePage.GetHomePageValue<IPublishedContent>("siteLogo");

    IPublishedContent loginPage = member == null ? LoginPage : null;
    string loginUrl = loginPage != null ? loginPage.Url : null;
    string loginButtonText = member == null ? homePage.GetHomePageValue<string>("loginButtonText") : null;

    IPublishedContent registerPage = member == null ? homePage.GetHomePageValue<IPublishedContent>("registerPage") : null;
    string registerUrl = registerPage != null ? registerPage.Url : null;
    string registerButtonText = member == null ? homePage.GetHomePageValue<string>("registerButtonText") : null;

    IPublishedContent profilePage = member != null ? memberModel.Chapter.GetPropertyValue<IPublishedContent>("profilePage") : null;
    string profileUrl = profilePage != null ? profilePage.Url : null;

    IPublishedContent adminPage = memberModel != null && memberModel.AdminUserId != null ? memberModel.Chapter.GetPropertyValue<IPublishedContent>("adminPage") : null;
    string adminUrl = adminPage != null ? adminPage.Url : null;

    string logoutButtonText = member != null ? homePage.GetHomePageValue<string>("logoutButtonText") : null;
    string logoutUrl = "/umbraco/surface/account/logout";
}

@if (logo != null)
{
    <div class="bg-dark text-center">
        <a href="@homePage.Url"><img class="logo--main" src="@logo.Url" /></a>
    </div>
}

<nav class="navbar navbar--top navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        @if (logo == null)
        {
            <a class="navbar-brand" href="@homePage.Url">
                @homePage.Name
            </a>
        }

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse flex-column" id="navbarSupportedContent">
            @foreach (IEnumerable<IPublishedContent> menuItemGroup in menuItemGroups)
            {
                <ul class="navbar-nav mr-auto">
                    @foreach (var item in menuItemGroup)
                    {
                        <li class="nav-item">
                            <a class="nav-link @(item.IsAncestorOrSelf(Model.Content) ? "active" : null)" href="@item.Url">@item.Name</a>
                        </li>
                    }
                </ul>
            }
        </div>

        <div class="account-links align-middle-x">
            @if (member == null)
            {
                <a class="btn btn-primary" href="@loginUrl">@loginButtonText</a>

                if (!string.IsNullOrEmpty(registerUrl))
                {
                    <a class="btn btn-success" href="@registerUrl">@registerButtonText</a>
                }
            }
            else
            {
                <div class="dropdown">
                    <div class="text-light account-links__user" data-toggle="dropdown">
                        <i class="fa fa-user-o fa-2x"></i>
                    </div>
                    <div class="dropdown-menu dropdown-menu-right" role="menu">
                        @if (!string.IsNullOrEmpty(profileUrl))
                        {
                            <a class="dropdown-item" href="@profileUrl">My profile</a>
                        }
                        <a class="dropdown-item" href="@memberModel.Chapter.Url">@memberModel.Chapter.Name</a>
                        @if (!string.IsNullOrEmpty(adminUrl))
                        {
                            <a class="dropdown-item" href="@adminUrl">Admin</a>
                            <a class="dropdown-item" href="/umbraco" target="_blank">Back office</a>
                        }
                        <a class="dropdown-item" href="@logoutUrl">@logoutButtonText</a>
                    </div>
                </div>
            }
        </div>
    </div>
</nav>